# SITE CONFIGURATION
url: predictiveecology.org

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "Predictive Ecology"
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "ecological forecasting models and data" # used by search engines

  # Header and footer text
  header_text: >
    <p>A blog about prediction in ecology: the science, the complexity and the computation</p>
  footer_text: >
    This blog is maintained by Eliot McIntire, a research scientist with the Government of Canada.<br/>All content is his own or that of contributors ("the lab"), and does not necessarily reflect any official policy of the Government of Canada.<br/><small>Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a></small>

  # Icons
  rss: false
  email_address: "eliot.mcintire@nrcan.gc.ca" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "PredictiveEcology"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "@eliotmcintire"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-58633549-2" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "predictiveecologyorg"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
gems:
  - jekyll-redirect-from
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

exclude: ["_posts/*.Rmd", "_posts/*.html", "_posts/.Rhistory"]
