project:
  type: website
  output-dir: docs
  preview:
    browser: false
    timeout: 0.001

website:
  title: "Predictive Ecology Community"
  description: "The Predictive Ecology Community website"
  favicon: "assets/logo/favicon-32x32.png"
  navbar:
    logo: "assets/logo/favicon-196x196.png"
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - SpaDES.qmd
      - Workshops.qmd
      - publications.qmd
      - presentations.qmd
      - icon: github
        href: https://github.com/PredictiveEcology
      - icon: twitter
        href: https://twitter.com/PredictiveEcol
  page-footer:
    left:
      - text: "This blog is maintained by Dr. Eliot McIntire, with contributions by Alex Chubaty, Ceres Barros, and Tati Micheletti. Powered by Quarto"
  sidebar:
    logo: "assets/logo/favicon-196x196.png"
  comments:
      hypothesis:
        theme: clean
        openSidebar: false
  google-analytics: "UA-58633549-2"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/css/main.scss
    smooth-scroll: true
    link-external-newwindow: true

editor: visual

execute:
  freeze: auto
