project:
  type: book

book:
  title: "training"
  author: "Norah Jones"
  date: "02/05/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - castorExample.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/css/main.scss
    smooth-scroll: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto


