project:
  type: book

book:
  title: "training"
  author:
    - "E. McIntire"
    - "C. Barros"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - part: NewModule.qmd
      chapters:
      - NewModuleIntro.qmd
    - part: realexamples.qmd
      chapters:
      - castorExample.qmd
    - references.qmd

bibliography: references/references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/css/main.scss
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto


